/*
 * Copyright (c) 2018, 2020 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.28 at 04:17:44 PM MSK 
//


package javasoft.sqe.jaxb.tgxml.testgen;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestTechnique }
     * 
     */
    public TestTechnique createTestTechnique() {
        return new TestTechnique();
    }

    /**
     * Create an instance of {@link ExpectedResultSideEffect }
     * 
     */
    public ExpectedResultSideEffect createExpectedResultSideEffect() {
        return new ExpectedResultSideEffect();
    }

    /**
     * Create an instance of {@link AssertionRef }
     * 
     */
    public AssertionRef createAssertionRef() {
        return new AssertionRef();
    }

    /**
     * Create an instance of {@link SupportCode }
     * 
     */
    public SupportCode createSupportCode() {
        return new SupportCode();
    }

    /**
     * Create an instance of {@link ExternalData }
     * 
     */
    public ExternalData createExternalData() {
        return new ExternalData();
    }

    /**
     * Create an instance of {@link SelectIf }
     * 
     */
    public SelectIf createSelectIf() {
        return new SelectIf();
    }

    /**
     * Create an instance of {@link TestGroup }
     * 
     */
    public TestGroup createTestGroup() {
        return new TestGroup();
    }

    /**
     * Create an instance of {@link TestGroupAttributes }
     * 
     */
    public TestGroupAttributes createTestGroupAttributes() {
        return new TestGroupAttributes();
    }

    /**
     * Create an instance of {@link Remote }
     * 
     */
    public Remote createRemote() {
        return new Remote();
    }

    /**
     * Create an instance of {@link DocElem }
     * 
     */
    public DocElem createDocElem() {
        return new DocElem();
    }

    /**
     * Create an instance of {@link TestCaseDocumentation }
     * 
     */
    public TestCaseDocumentation createTestCaseDocumentation() {
        return new TestCaseDocumentation();
    }

    /**
     * Create an instance of {@link TargetSpec }
     * 
     */
    public TargetSpec createTargetSpec() {
        return new TargetSpec();
    }

    /**
     * Create an instance of {@link CodeSet }
     * 
     */
    public CodeSet createCodeSet() {
        return new CodeSet();
    }

    /**
     * Create an instance of {@link ExpectedResultException }
     * 
     */
    public ExpectedResultException createExpectedResultException() {
        return new ExpectedResultException();
    }

    /**
     * Create an instance of {@link LibraryDocumentation }
     * 
     */
    public LibraryDocumentation createLibraryDocumentation() {
        return new LibraryDocumentation();
    }

    /**
     * Create an instance of {@link TestCaseAttributes }
     * 
     */
    public TestCaseAttributes createTestCaseAttributes() {
        return new TestCaseAttributes();
    }

    /**
     * Create an instance of {@link SpecElem }
     * 
     */
    public SpecElem createSpecElem() {
        return new SpecElem();
    }

    /**
     * Create an instance of {@link RequiredResource }
     * 
     */
    public RequiredResource createRequiredResource() {
        return new RequiredResource();
    }

    /**
     * Create an instance of {@link Lib }
     * 
     */
    public Lib createLib() {
        return new Lib();
    }

    /**
     * Create an instance of {@link ExternalSupportClass }
     * 
     */
    public ExternalSupportClass createExternalSupportClass() {
        return new ExternalSupportClass();
    }

    /**
     * Create an instance of {@link InlineData }
     * 
     */
    public InlineData createInlineData() {
        return new InlineData();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link TestCaseSpec }
     * 
     */
    public TestCaseSpec createTestCaseSpec() {
        return new TestCaseSpec();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link LibraryAttributes }
     * 
     */
    public LibraryAttributes createLibraryAttributes() {
        return new LibraryAttributes();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link Export }
     * 
     */
    public Export createExport() {
        return new Export();
    }

    /**
     * Create an instance of {@link InlineAssertion }
     * 
     */
    public InlineAssertion createInlineAssertion() {
        return new InlineAssertion();
    }

    /**
     * Create an instance of {@link TestCode }
     * 
     */
    public TestCode createTestCode() {
        return new TestCode();
    }

    /**
     * Create an instance of {@link TestCase }
     * 
     */
    public TestCase createTestCase() {
        return new TestCase();
    }

    /**
     * Create an instance of {@link AttrElem }
     * 
     */
    public AttrElem createAttrElem() {
        return new AttrElem();
    }

    /**
     * Create an instance of {@link TestGroupDocumentation }
     * 
     */
    public TestGroupDocumentation createTestGroupDocumentation() {
        return new TestGroupDocumentation();
    }

    /**
     * Create an instance of {@link TargetSpecElem }
     * 
     */
    public TargetSpecElem createTargetSpecElem() {
        return new TargetSpecElem();
    }

    /**
     * Create an instance of {@link Library }
     * 
     */
    public Library createLibrary() {
        return new Library();
    }

    /**
     * Create an instance of {@link InlineSupportClass }
     * 
     */
    public InlineSupportClass createInlineSupportClass() {
        return new InlineSupportClass();
    }

    /**
     * Create an instance of {@link Dependency }
     * 
     */
    public Dependency createDependency() {
        return new Dependency();
    }

    /**
     * Create an instance of {@link Precondition }
     * 
     */
    public Precondition createPrecondition() {
        return new Precondition();
    }

}
