|Schema Compiler |A schema compiler generates Java source files or
compiled classes that represent XML data described by W3C XML Schema
recommendation [XSD Part 1][XSD Part 2].

|Schema Compiler Output |The output of a Schema Compiler intended to be
run in combination with the Libraries.

|Schema Generator |A software development tool that maps a set of
existing Java sources or class files to Schema Generator Output. The
mapping is described by program annotations. The Schema Generator can
be invoked directly by a programmer without programming.

|Schema Generator Output |The output of a Schema Generator intended to be
a W3C XML Schema defined in the XML Schema recommendation
[XSD Part 1][XSD Part 2]. The output of a Schema Generator that is in
the format defined by the W3C XML Schema recommendation
[XSD Part 1][XSD Part 2].
