type=page
status=published
title=Introduction
next=rules.html
prev=preface.html
~~~~~~
include::attributes.conf[]
Introduction
============

[[GBFOW]]


[[introduction]]
1 Introduction
--------------

This chapter provides an overview of the principles that apply
generally to all Technology Compatibility Kits (TCKs) and describes the
{TechnologyFullName} TCK {TechnologyVersion} (JSR {JSR}). It also includes a high level listing
of what is needed to get up and running with the {TechnologyShortName}
TCK.

This chapter includes the following topics:

* link:#GBFTK[Compatibility Testing]
* link:#GBFQR[About the TCK]
* link:#GBFQW[Getting Started With the TCK]

[[GBFTK]][[compatibility-testing]]

1.1 Compatibility Testing
~~~~~~~~~~~~~~~~~~~~~~~~~

Compatibility testing differs from traditional product testing in a
number of ways. The focus of compatibility testing is to test those
features and areas of an implementation that are likely to differ across
other implementations, such as those features that:

* Rely on hardware or operating system-specific behavior
* Are difficult to port
* Mask or abstract hardware or operating system behavior

Compatibility test development for a given feature relies on a complete
specification and reference implementation for that feature.
Compatibility testing is not primarily concerned with robustness,
performance, or ease of use.

[[GBFQN]][[why-compatibility-testing-is-important]]

1.1.1 Why Compatibility Testing is Important
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Java platform compatibility is important to different groups involved
with Java technologies for different reasons:

* Compatibility testing ensures that the Java platform does not become
fragmented as it is ported to different operating systems and hardware
environments.
* Compatibility testing benefits developers working in the Java
programming language, allowing them to write applications once and then
to deploy them across heterogeneous computing environments without
porting.
* Compatibility testing allows application users to obtain applications
from disparate sources and deploy them with confidence.
* Conformance testing benefits Java platform implementors by ensuring a
level playing field for all Java platform ports.

[[GBFPR]][[tck-compatibility-rules]]

1.1.2 TCK Compatibility Rules
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compatibility criteria for all technology implementations are embodied
in the TCK Compatibility Rules that apply to a specified technology.
Each TCK tests for adherence to these Rules as described in
link:rules.html#GBFSN[Chapter 2, "Procedure for Certification."]

[[GBFPW]][[tck-overview]]

1.1.3 TCK Overview
^^^^^^^^^^^^^^^^^^

A TCK is a set of tools and tests used to verify that a licensee's
implementation of a Java EE technology conforms to the applicable
specification. All tests in the TCK are based on the written
specifications for the Java platform. A TCK tests compatibility of a
licensee's implementation of the technology to the applicable
specification of the technology. Compatibility testing is a means of
ensuring correctness, completeness, and consistency across all
implementations developed by technology licensees.

The set of tests included with each TCK is called the test suite. Most
tests in a TCK's test suite are self-checking, but some tests may
require tester interaction. Most tests return either a Pass or Fail
status. For a given platform to be certified, all of the required tests
must pass. The definition of required tests may change from platform to
platform.

The definition of required tests will change over time. Before your
final certification test pass, be sure to download the latest Exclude
List for the TCK you are using.

[[GBFPB]][[java-community-process-jcp-program-and-compatibility-testing]]

1.1.4 Java Community Process (JCP) Program and Compatibility Testing
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The Java Community Process (JCP) program is the formalization of the
open process that has been used since 1995 to develop and revise Java
technology specifications in cooperation with the international Java
community. The JCP program specifies that the following three major
components must be included as deliverables in a final Java technology
release under the direction of the responsible Expert Group:

* Technology Specification
* Reference Implementation
* Technology Compatibility Kit (TCK)

For further information about the JCP program, go to Java Community
Process (http://jcp.org/en/home/index).

[[GBFQR]][[about-the-tck]]

1.2 About the TCK
~~~~~~~~~~~~~~~~~

The {TechnologyShortName} TCK {TechnologyVersion} is designed as a
portable, configurable, automated test suite for verifying the
compatibility of a licensee's implementation of the
{TechnologyShortName} {TechnologyVersion} Specification.

[[GBFQV]][[tck-specifications-and-requirements]]

1.2.1 TCK Specifications and Requirements
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This section lists the applicable requirements and specifications.

* Specification Requirements: Software requirements for a
{TechnologyShortName} implementation are described in detail in the
{TechnologyShortName} {TechnologyVersion} Specification.  Links to the
{TechnologyShortName} specification and other product information can
be found at {JSRURL}.
* {TechnologyShortName} Version: The {TechnologyShortName} TCK
{TechnologyVersion} is based on the {TechnologyShortName}
Specification, Version {TechnologyVersion}.
* JavaTest harness: The {TechnologyShortName} TCK
{TechnologyVersion} requires the JavaTest harness, Version {JavaTestVersion}.
* Reference Implementation: See the RI documentation page at
{TechnologyRIURL} for more information.

[[GBFSQ]][[tck-components]]

1.2.2 TCK Components
^^^^^^^^^^^^^^^^^^^^

The {TechnologyShortName} TCK {TechnologyVersion} includes the
following components:

* JavaTest harness version {JavaTestVersion} and related documentation. See the
`ReleaseNotes-jtharness.html` file and the
link:https://wiki.openjdk.java.net/display/CodeTools/JT+Harness[JT Harness web site]
for additional information.
* {TechnologyShortName} TCK signature tests; check that all public APIs
are supported and/or defined as specified in the {TechnologyShortName}
Version {TechnologyVersion} implementation under test.
* API tests for all of the {TechnologyShortName} API in all related packages:
include::packages.inc[]
* End-to-end tests that demonstrate compliance with the {TechnologyFullName}
Specification.
* The TCK interview component, which is used to configure a test run.
* Various scripts and Java classes used to run the Reference Implementation
schema compiler/generator, which can also be adapted to run your own schema
compiler/generator implementation.
* The test suite, which is a collection of tests and supplemental files that provide
data for the automatic running of tests through the JavaTest harness.
* An exclude list, which provides a list of tests that your implementation is not
required to pass.
* TCK documentation, including Release Notes, JavaTest User’s Guide, and JAXB
TCK User’s Guide.

The {TechnologyShortName} TCK tests run on the following platforms:

* Windows 10 x64
* Oracle Linux 7.1 x64

[[GBFSA]][[javatest-harness]]

1.2.3 JavaTest Harness
^^^^^^^^^^^^^^^^^^^^^^

The JavaTest harness version {JavaTestVersion} is a set of tools
designed to run and manage test suites on different Java platforms. The
JavaTest harness can be described as both a Java application and a set
of compatibility testing tools. It can run tests on different kinds of
Java platforms and it allows the results to be browsed online within
the JavaTest GUI, or offline in the HTML reports that the JavaTest
harness generates.

The JavaTest harness includes the applications and tools that are used
for test execution and test suite management. It supports the following
features:

* Sequencing of tests, allowing them to be loaded and executed automatically
* Graphic user interface (GUI) for ease of use
* Automated reporting capability to minimize manual errors
* Failure analysis
* Test result auditing and auditable test specification framework
* Distributed testing environment support

To run tests using the JavaTest harness, you specify which tests in the
test suite to run, how to run them, and where to put the results as
described in link:config.html#GBFVV[Chapter 4, "Setup and
Configuration."]

Test Agents
^^^^^^^^^^^
A test agent is a small Java application that is used in conjunction with the JavaTest
harness to run tests on a Java platform on which it is not possible or desirable to run
the main JavaTest harness. The agent that is running on the test platform responds to
requests from the JavaTest harness that is running elsewhere.
If the JavaTest harness and the technology you are testing are being run on different
systems, then you must install an agent on the system being tested.

The {TechnologyShortName} TCK {TechnologyVersion} uses the JavaTest agent provided with the JavaTest harness
version {JavaTestVersion}. The JavaTest agent uses a bidirectional serial connection supporting
both TCP/IP and RS-232 protocols to communicate between the test system and the
JavaTest harness. Other types of serial connections, such as infrared, parallel, USB,
and firewire can be added through the JavaTest API and modeled on the existing
serial system.

The JavaTest harness includes an Agent Monitor window that you can use to control
and monitor agents.


[[GBFRA]][[tck-compatibility-test-suite]]

1.2.4 TCK Compatibility Test Suite
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The test suite is the collection of tests used by the JavaTest harness
to test a particular technology implementation. In this case, it is the
collection of tests used by the {TechnologyShortName} TCK
{TechnologyVersion} to test a {TechnologyShortName} {TechnologyVersion}
implementation. The tests are designed to verify that a licensee's
runtime implementation of the technology complies with the appropriate
specification. The individual tests correspond to assertions of the
specification.

The tests that make up the TCK compatibility test suite are precompiled
and indexed within the TCK test directory structure. When a test run is
started, the JavaTest harness scans through the set of tests that are
located under the directories that have been selected. While scanning,
the JavaTest harness selects the appropriate tests according to any
matches with the filters you are using and queues them up for execution.

{TechnologyShortName} TCK {TechnologyVersion} test suite comprises six tests
categories:
* Schema to Java mapping tests
* Java to schema mapping tests
* JAXB framework API tests
* Content tree tests
* XML-to-Java name convention tests
* XML validation tests

Schema Compiler Tests
^^^^^^^^^^^^^^^^^^^^^
The schema compiler tests verify the following:
1. The schema compiler finds errors in invalid schema.
2. The schema compiler successfully compiles valid schema and the signatures of
generated Java classes are appropriate.
3. The schema compiler appropriately compiles schema annotated with {TechnologyShortName}
custom binding declarations:
* Successfully compiles valid source schema with well-formed binding
declarations.
* Fails to compile valid source schema with non-well-formed binding
declarations.

JAXB Framework API Tests
^^^^^^^^^^^^^^^^^^^^^^^^
The JAXB framework API tests cover public classes and interfaces defined in the
`javax.xml.bind` package and sub-packages.

Content Tree Tests
^^^^^^^^^^^^^^^^^^
The content tree tests test the classes generated by the {TechnologyShortName}
schema compiler, including:
1. Unmarshalling valid documents: the documents must be unmarshalled and
validated correctly.
2. Marshalling documents: invokes marshalling for valid documents and checks that
no errors are reported.
3. Content tree evaluating: check data in content tree after unmarshalling.
4. Content tree validating: modify data in content tree to make the tree invalid and, if
the modification does not report an error, then enable {TechnologyShortName}
{TechnologyVersion} validation on Marshaller, and verify that Marshaller reports the error.

XML-to-Java Name Conversion Tests
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The XML-to-Java name conversion tests check that XML-to-Java name conversion
rules are implemented correctly and support most of the Unicode characters that are
allowed for XML names.

Schema Generator Tests
^^^^^^^^^^^^^^^^^^^^^^
The schema generator tests verify that:
1. The schema generator supports all the Java Types to XML mapping.
2. The schema generator appropriately maps Java program elements to XML
Schema constructs.
3. The schema generator appropriately maps Java program elements that are
customized using mapping annotations and program annotations that are based
on JSR–175 program annotation facility:
* Successfully generates valid target schema from correctly annotated Java
program element.
* Fails to process annotated Java program elements that have constraint
violations as specified in the `Java Types to XML` section of the {TechnologyShortName}
{TechnologyVersion} specification and `javax.xml.bind.annotation` javadocs.
* The schema generator successfully produces a well-formed schema; all
documents expected to be valid against generated schema are valid and all
documents expected to be invalid against generated schema are invalid.

XML Validation Tests
^^^^^^^^^^^^^^^^^^^^
XML Validation tests are designed to check schema validation when a mechanisms
other than JAXP is used. Note that XML validation tests are mandatory when XML
validation is not performed via JAXP.

[[GBFSH]][[exclude-lists]]

1.2.5 Exclude Lists
^^^^^^^^^^^^^^^^^^^

Each version of a TCK includes an Exclude List contained in a `.jtx`
file. This is a list of test file URLs that identify tests which do not
have to be run for the specific version of the TCK being used. Whenever
tests are run, the JavaTest harness automatically excludes any test on
the Exclude List from being executed.

A licensee is not required to pass or run any test on the Exclude List.
The Exclude List file, +{jtxFileName}+, is included in the
{TechnologyShortName} TCK.


[NOTE]
=======================================================================

You should always make sure you are using an up-to-date copy of the
Exclude List before running the {TechnologyShortName} TCK to verify your
implementation.

=======================================================================


A test might be in the Exclude List for reasons such as:

* An error in an underlying implementation API has been discovered which
does not allow the test to execute properly.
* An error in the specification that was used as the basis of the test
has been discovered.
* An error in the test itself has been discovered.
* The test fails due to a bug in the tools (such as the JavaTest
harness, for example).

In addition, all tests are run against the reference implementations.
Any tests that fail when run on a reference Java platform are put on the
Exclude List. Any test that is not specification-based, or for which the
specification is vague, may be excluded. Any test that is found to be
implementation dependent (based on a particular thread scheduling model,
based on a particular file system behavior, and so on) may be excluded.


[NOTE]
=======================================================================

Licensees are not permitted to alter or modify Exclude Lists. Changes to
an Exclude List can only be made by using the procedure described in
link:rules.html#CJAJEAEI[Section 2.3.1, "TCK Test Appeals Steps."]

=======================================================================


[[GBFRR]][[tck-configuration]]

1.2.6 TCK Configuration
^^^^^^^^^^^^^^^^^^^^^^^

Use the JavaTest harness GUI to configure and run the {TechnologyShortName} TCK tests as described in
link:config.html#GBFVV[Chapter 4, "Setup and Configuration."]

[[GBFQW]][[getting-started-with-the-tck]]

1.3 Getting Started With the TCK
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This section provides an general overview of what needs to be done to
install, set up, test, and use the {TechnologyShortName} TCK. These
steps are explained in more detail in subsequent chapters of this
guide.

1.  Make sure that the following software has been correctly installed
on the system hosting the JavaTest harness:
/// include::req-software.inc[]
* Java SE {SEversion} on the system hosting the JavaTest harness.
* {TechnologyShortName} software: The implementation of the {TechnologyShortName} {TechnologyVersion}
specification under test on the appropriate host platform and the JavaTest
harness can access it through the appropriate protocol (for example, TCP/IP).
* Java EE 8.0 RI, which is {TechnologyRI}
* The {TechnologyShortName} {TechnologyVersion} Vendor Implementation (VI) +
See the documentation for each of these software applications for
installation instructions.
2. Install the {TechnologyShortName} TCK {TechnologyVersion} software on the
system that is hosting the JavaTest harness. See link:install.html#GBFTP[Chapter 3,
"Installation,"] for instructions on installing the {TechnologyShortName} TCK.
The JavaTest harness version {JavaTestVersion} is packaged with the {TechnologyShortName} TCK
and is installed as part of the {TechnologyShortName} TCK installation.
3.  Start and configure the JavaTest harness. Start the JavaTest harness, specify a
working directory, and complete the configuration interview. +
See link:config.html#GBFVV[Chapter 4, "Setup and Configuration,"] for
details about the following steps.
  a.  Set up your shell environment.
  b.  Modify the required properties.
  c.  Configure the JavaTest harness.
4.  Test the {TechnologyShortName} {TechnologyVersion} implementation. +
Test the {TechnologyShortName} implementation installation by running
the test suite.  See link:using.html#GBFWO[Chapter 5, "Executing Tests."]
5.  Generate a test report, if required. Select Report then New Report to generate
the reports about your test runs. See link:using.html#GBFVK[Section 5.6, "Test Reports."]
